import Header from "./Header/Header";
import Footer from "./Footer/Footer";
import Head from "next/head";

const Layout = ({children, headerType}) => {
    return (
        <>
            <Head>
                <title>aLrent</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
                
            </Head>

            <Header headerType={headerType}/>
            {children}
            <Footer/>
        </>
    );
};

export default Layout;